# Generated by Django 5.2 on 2025-06-21 16:41

import django.db.models.deletion
import main.models
import main.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID аккаунта')),
                ('entry', models.CharField(max_length=128, verbose_name='Ссылка на xml')),
                ('google_dir', models.CharField(max_length=64, verbose_name='ID google папки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('marker', models.CharField(max_length=64, verbose_name='Маркер для описания')),
                ('marker_padding', models.PositiveSmallIntegerField(default=0, help_text='Если маркер не нужно учитывать, укажите длину маркера', verbose_name='Отступ после маркера')),
                ('google_cred', models.FileField(default='', storage=main.storages.AccountStorage, upload_to='accounts/', verbose_name='Файл google_cred.json')),
                ('is_cities', models.BooleanField(default=False, verbose_name='Умножение по городам')),
                ('cities', models.TextField(blank=True, default=None, help_text='Указывать через |', null=True, verbose_name='Список городов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Модель аккаунта',
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=main.models.banner_file_name, verbose_name='Изображение')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account', verbose_name='Ссылка на пользователя')),
            ],
            options={
                'verbose_name': 'Изображения плашек',
                'verbose_name_plural': 'Изображения плашек',
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=main.models.store_file_name, verbose_name='Изображение')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account', verbose_name='Ссылка на пользователя')),
            ],
            options={
                'verbose_name': 'Изображения магазина',
                'verbose_name_plural': 'Изображения магазина',
            },
        ),
    ]
