# Generated by Django 5.2 on 2025-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID аккаунта')),
                ('entry', models.CharField(max_length=128, verbose_name='Ссылка на вход')),
                ('google_dir', models.CharField(max_length=64, verbose_name='ID google папки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('marker', models.CharField(max_length=64, verbose_name='Маркер для описания')),
                ('marker_padding', models.IntegerField(default=0, verbose_name='Отступ после маркера')),
                ('png_banner', models.IntegerField(verbose_name='Фото png плашки')),
                ('is_cities', models.BooleanField(default=False, verbose_name='Умножение по городам')),
                ('cities', models.TextField(blank=True, default=None, null=True, verbose_name='Список городов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Модель аккаунта',
            },
        ),
    ]
