# Generated by Django 5.2 on 2025-05-18 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='overlay_images',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='shop_images',
        ),
        migrations.AlterField(
            model_name='organization',
            name='watermark_path',
            field=models.FileField(blank=True, help_text='Основное изображение для наложения (если не указаны другие)', null=True, upload_to='watermark_files/', verbose_name='Основной водяной знак'),
        ),
        migrations.CreateModel(
            name='OverlayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='overlay_images/', verbose_name='Изображение для наложения')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('position', models.IntegerField(default=0, help_text='Порядок применения (0 - первое изображение товара, 1 - второе и т.д.)', verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_images', to='main.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Изображение для наложения',
                'verbose_name_plural': 'Изображения для наложения',
                'ordering': ['organization', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/', verbose_name='Изображение магазина')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('position', models.IntegerField(default=0, help_text='Порядок добавления (меньшее значение - раньше в списке)', verbose_name='Позиция')),
                ('use_for_collage', models.BooleanField(default=False, help_text='Если отмечено, это изображение будет использоваться для создания коллажа с первым фото товара', verbose_name='Использовать для коллажа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_images', to='main.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Изображение магазина',
                'verbose_name_plural': 'Изображения магазина',
                'ordering': ['organization', 'position'],
            },
        ),
    ]
