# Generated by Django 5.2 on 2025-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID аккаунта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cities',
            field=models.TextField(blank=True, default=None, help_text='Указывать через |', null=True, verbose_name='Список городов'),
        ),
        migrations.AlterField(
            model_name='account',
            name='entry',
            field=models.CharField(max_length=128, verbose_name='Ссылка на xml'),
        ),
        migrations.AlterField(
            model_name='account',
            name='marker_padding',
            field=models.PositiveSmallIntegerField(default=0, help_text='Если маркер не нужно учитывать, укажите длину маркера', verbose_name='Отступ после маркера'),
        ),
    ]
