# Generated by Django 5.2 on 2025-06-22 08:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_google_cred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='google_cred',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='/accounts'), upload_to='accounts/', verbose_name='Файл google_cred.json'),
        ),
    ]
