# Generated by Django 5.2 on 2025-06-22 08:45

import django.core.files.storage
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_account_google_cred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='google_cred',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Khamz\\Программирование\\Проекты\\Работа\\J_GET\\projects\\📌В процессе\\new_avito\\avito_add_image/accounts'), upload_to=main.models.google_cred_file_name, verbose_name='Файл google_cred.json'),
        ),
    ]
