# Generated by Django 5.2 on 2025-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_account_google_cred'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_ident',
            field=models.CharField(default=0, help_text='Название или имя', max_length=64, verbose_name='Идентификатор аккаунта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(auto_created=True, default=0, editable=False, primary_key=True, serialize=False, verbose_name='ID аккаунта'),
        ),
    ]
