# Generated by Django 5.2 on 2025-06-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_account_account_ident_alter_account_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.AutoField(auto_created=True, default=0, editable=False, primary_key=True, serialize=False, verbose_name='ID аккаунта'),
        ),
    ]
