# Generated by Django 5.2 on 2025-06-22 21:46

import django.core.files.storage
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_account_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Khamz\\Программирование\\Проекты\\Работа\\J_GET\\projects\\📌В процессе\\new_avito\\avito_add_image/accounts'), upload_to=main.models.banner_file_name, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Khamz\\Программирование\\Проекты\\Работа\\J_GET\\projects\\📌В процессе\\new_avito\\avito_add_image/accounts'), upload_to=main.models.store_file_name, verbose_name='Изображение'),
        ),
    ]
